version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    networks:
      - laravel

  caddy:
    image: caddy:2-alpine
    ports:
      - "3000:80"
    volumes:
      - .:/var/www
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - php
    networks:
      - laravel

  pgsql:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    networks:
      - laravel

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  pgsql_data:
  redis_data:
