name: Test Container Registry

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  push-test-image:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push Laravel PHP image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/laravel-php:latest
        
    - name: Build and push Caddy image
      uses: docker/build-push-action@v4
      with:
        context: ./caddy
        file: ./caddy/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/laravel-caddy:latest
