name: Test Container Registry

on:
  push:
    branches: [ main ]

jobs:
  push-test-image:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push PHP image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/php:latest
        
    - name: Build and push Caddy image
      uses: docker/build-push-action@v4
      with:
        context: ./docker
        file: ./docker/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/caddy:latest
